# agent 的名称
id: "ocr_tool"
# 对 agent 的详细描述
description: "OCR 工具"
# agent 角色扮演相关
title: "ocr_tool"
# agent 关键词
keywords: [ "OCR", "工具" ]
# agent 用户手册
manual: "http://wechat.com/xxxx.html"


# 执行上下文参数
params:
  - name: "ocr_file_name"
    title: "ocr_file_name"
    type: "str"
    notnull: true
    description: "OCR 文件名称"
    defaultValue: ""
  

# 执行上下文结果
results:
  - name: "ocr_result"
    title: "ocr_result"
    type: "str"
    notnull: true
    description: "OCR 识别结果"
    defaultValue: ""