# group 名称
id: "AgentGroup1"
# 对 group 的详细描述
description: "智能体组1"
# group 要完成的任务
title: "获取微信服务号签名"
# group 关键词
keywords: [ "微信", "签名", "微信服务号信息服务" ]
# group 要部署的机器
reference: "http://xxx/Scheduling/机器ID"
# group 用户手册
manual: "http://wechat.com/xxxx.html"

# group 内包含的 agent
agents:
  - Agent1

routes:
  - source: "start"
    target: "Agent1"
    type: "hard"


# 最大执行步数
max_step: 100

# 执行上下文参数
params:
  - name: "number1"
    type: "str"
  - name: "number2"
    type: "str"
  - name: "true_result"
    type: "str"

# 执行上下文结果
results:
  - name: "result"
    title: "计算结果"
    notnull: true
    description: ""
    defaultValue: ""
    type: "String"
  - name: "bool_result"
    type: "str"


# group 场景下的 prompt
prompts: "组级别提示词"
